import React, { useEffect, useState } from 'react';
import SlideLayout from './SlideLayout';
import { MapPin, Calendar, Users, Globe, Loader2, Sparkles } from 'lucide-react';
import { GoogleGenAI } from "@google/genai";

const IntroSlide: React.FC = () => {
  const [heroImage, setHeroImage] = useState<string>("https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&q=80&w=1200");
  const [isGenerating, setIsGenerating] = useState<boolean>(true);

  useEffect(() => {
    const generateAiImage = async () => {
      try {
        const apiKey = process.env.API_KEY;
        if (!apiKey) return;

        const ai = new GoogleGenAI({ apiKey });
        
        // Using 'gemini-2.5-flash-image' (Nano Banana) as requested
        const response = await ai.models.generateContent({
          model: 'gemini-2.5-flash-image',
          contents: {
            parts: [{
              text: 'A professional, futuristic 3D concept art symbolizing "AI Cooperation between South Korea and Colombia". The image should feature a glowing digital network connecting a stylized map of Korea and Colombia. Incorporate the colors of the flags: Red and Blue (Korea) mixed with Yellow, Blue, and Red (Colombia) in a harmonious, high-tech aesthetic. Elements of neural networks, data streams, and a handshake formed by digital particles. Cinematic lighting, 8k resolution, business presentation style.'
            }]
          }
        });

        if (response.candidates?.[0]?.content?.parts) {
          for (const part of response.candidates[0].content.parts) {
            if (part.inlineData) {
              setHeroImage(`data:image/png;base64,${part.inlineData.data}`);
              break;
            }
          }
        }
      } catch (error) {
        console.error("AI Image Generation failed, falling back to default:", error);
      } finally {
        setIsGenerating(false);
      }
    };

    generateAiImage();
  }, []);

  return (
    <SlideLayout title="KOICA AI ODA 협력 현지조사" subtitle="보고타, 콜롬비아 (Bogotá D.C.)">
      <div className="grid grid-cols-12 grid-rows-6 gap-4 h-full">
        
        {/* Hero Image / Main Visual */}
        <div className="col-span-8 row-span-6 relative rounded-2xl overflow-hidden shadow-sm group bg-slate-900">
          <img 
            src={heroImage} 
            alt="Global AI Connection" 
            className={`w-full h-full object-cover transition-all duration-1000 ${isGenerating ? 'opacity-50 blur-sm scale-105' : 'opacity-100 scale-100 group-hover:scale-105'}`}
          />
          
          {isGenerating && (
            <div className="absolute inset-0 flex flex-col items-center justify-center z-20">
              <div className="bg-white/10 backdrop-blur-md border border-white/20 px-6 py-3 rounded-full flex items-center gap-3 text-white shadow-xl animate-pulse">
                <Loader2 className="animate-spin text-yellow-400" size={20} />
                <span className="font-medium text-sm tracking-wide">AI Generating Visuals (Nano Banana)...</span>
              </div>
            </div>
          )}

          {!isGenerating && (
             <div className="absolute top-4 right-4 bg-black/40 backdrop-blur-sm border border-white/10 px-3 py-1 rounded-full flex items-center gap-2 text-[10px] text-white/80 z-20">
               <Sparkles size={10} className="text-yellow-400" />
               <span>Generated by Gemini 2.5</span>
             </div>
          )}

          <div className="absolute inset-0 bg-gradient-to-t from-blue-900/90 via-blue-900/30 to-transparent flex flex-col justify-end p-8 z-10">
            <h3 className="text-white text-4xl font-bold mb-2 drop-shadow-lg">Korea-Colombia AI Partnership</h3>
            <p className="text-blue-100 text-lg drop-shadow-md">
              콜롬비아의 디지털 전환과 한국의 AI 기술력이 만나는 새로운 협력의 장
            </p>
          </div>
        </div>

        {/* Info Card 1: Location */}
        <div className="col-span-4 row-span-2 bg-slate-50 p-6 rounded-2xl border border-slate-200 flex flex-col justify-center hover:bg-white hover:shadow-md transition-all">
          <div className="flex items-center gap-3 mb-2 text-blue-700">
            <MapPin size={24} />
            <span className="font-bold text-lg">조사 지역</span>
          </div>
          <p className="text-slate-700 font-medium text-xl">Colombia, Bogotá D.C.</p>
          <p className="text-slate-500 text-sm mt-1">DNP (국가기획처), MinTIC (정보통신부)</p>
        </div>

        {/* Info Card 2: Period */}
        <div className="col-span-4 row-span-2 bg-slate-50 p-6 rounded-2xl border border-slate-200 flex flex-col justify-center hover:bg-white hover:shadow-md transition-all">
          <div className="flex items-center gap-3 mb-2 text-blue-700">
            <Calendar size={24} />
            <span className="font-bold text-lg">조사 기간</span>
          </div>
          <p className="text-slate-700 font-medium text-xl">2026. 01. 28 - 2026. 02. 04</p>
          <p className="text-slate-500 text-sm mt-1">총 8일간의 현지 심층 분석</p>
        </div>

        {/* Info Card 3: Objective */}
        <div className="col-span-4 row-span-2 bg-blue-900 p-6 rounded-2xl flex flex-col justify-center text-white shadow-lg relative overflow-hidden">
           <div className="absolute top-0 right-0 w-24 h-24 bg-yellow-400 rounded-full blur-2xl opacity-20 transform translate-x-10 -translate-y-10"></div>
          <div className="flex items-center gap-3 mb-2 text-yellow-400 relative z-10">
            <Globe size={24} />
            <span className="font-bold text-lg">조사 목적</span>
          </div>
          <p className="font-medium text-lg relative z-10 leading-snug break-keep">
            콜롬비아 정부 기관 대상,<br/> 
            AI 수준 진단 및 ODA 협력 방안 조사
          </p>
        </div>

      </div>
    </SlideLayout>
  );
};

export default IntroSlide;